// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Mods.TechTree;
    using Eco.Shared.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;


    public partial class BlankTalent : Talent
    {
        public override bool Base => true;
    }

    [Serialized]
    [LocDisplayName("DOES NOTHING.")]
    public partial class AnimalHusbandryBlankTalentPlaceholderTalentGroup : TalentGroup
    {
        public override LocString DisplayDescription { get; } = Localizer.DoStr("This talent does nothing and should be avoided. Do not select this as your talent.");

        public AnimalHusbandryBlankTalentPlaceholderTalentGroup()
        {
            Talents = new Type[]
            {
            
            typeof(AnimalHusbandryBlankTalentPlaceholderTalent), 
            
  
            
            };
            this.OwningSkill = typeof(AnimalHusbandrySkill);
            this.Level = 6;
        }
    }

    
    [Serialized]
    public partial class AnimalHusbandryBlankTalentPlaceholderTalent : BlankTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(AnimalHusbandryBlankTalentPlaceholderTalentGroup); } }
        public AnimalHusbandryBlankTalentPlaceholderTalent()
        {
            this.Value = 6;
        }
    }
    

    
}