// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

using Eco.Gameplay.Skills;
using Eco.Shared.Localization;
using Eco.Shared.Serialization;
using System;
using System.Diagnostics;

namespace Eco.Mods.TechTree
{
    [Serialized]
    [LocDisplayName("Frugal Workspace: AnimalHusbandry")]
    public class AnimalHusbandryFrugalWorkspaceTalentGroup : TalentGroup
    {
        public override LocString DisplayDescription { get; } = Localizer.DoStr("Lowers the tier requirement of related tables by 0.2");

        public AnimalHusbandryFrugalWorkspaceTalentGroup()
        {
            this.Talents = new Type[1]
            {
        typeof (AnimalHusbandryFrugalReqTalent)
            };
            this.OwningSkill = typeof(AnimalHusbandrySkill);
            this.Level = 6;
        }
    }
	
	[Serialized]
    public class AnimalHusbandryFrugalReqTalent : FrugalWorkspaceTalent
    {
        public override bool Base
        {
            get
            {
                return false;
            }
        }

        public override Type TalentGroupType
        {
            get
            {
                return typeof(AnimalHusbandryFrugalWorkspaceTalentGroup);
            }
        }

        public AnimalHusbandryFrugalReqTalent()
        {
            this.Value = -0.2f;
        }
    }
}