// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
	using Eco.Shared.Utils;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Fresh Milk")]
    [Tag("Raw Food", 1)]
    [Weight(10)]
    [Ecopedia("Food", "Produce", createAsSubPage: true)]
    public partial class FreshMilkItem : FoodItem
    {
        public override LocString DisplayNamePlural     => Localizer.DoStr("Fresh Milk");
        public override LocString DisplayDescription    => Localizer.DoStr("Fresh milk straight out of a cow.");
        
        public override float Calories                  => 120;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 3, Fat = 7, Protein = 10, Vitamins = 0};
		protected override int BaseShelfLife => (int)TimeUtil.HoursToSeconds(72);
    }

}
