// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>
    [RequiresSkill(typeof(ButcherySkill), 1)] 
    public partial class HerbivoreLureRecipe :
        RecipeFamily
    {
        public HerbivoreLureRecipe()
        {
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "HerbivoreLure",
                    Localizer.DoStr("Herbivore Lure"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(CornItem), 5, typeof(ButcherySkill)), 
               new IngredientElement(typeof(FiddleheadsItem), 6, typeof(ButcherySkill)), 
               new IngredientElement(typeof(BeetItem), 5, typeof(ButcherySkill)),    
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<HerbivoreLureItem>(1),  
    
                    })
            };
            this.ExperienceOnCraft = 1;  
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(ButcherySkill)); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(HerbivoreLureRecipe), 4, typeof(ButcherySkill), typeof(ButcheryFocusedSpeedTalent), typeof(ButcheryParallelSpeedTalent));     
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Herbivore Lure"), typeof(HerbivoreLureRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(ButcheryTableObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
