// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
        using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>

    [Serialized]
    [LocDisplayName("Sheep")]
    [Weight(2000)]
    // Since latest update "Changed: Due to changing the tooltip system used for Ecopedia all item and object overrides will need to be adjusted, specifically the attribute "display: InPageTooltip.DynamicTooltip" for Ecopedia needs to be removed.
    [Ecopedia("Natural Resources", "Animal", createAsSubPage: true)]                                                                         
    public partial class SheepItem :
    Item                                    
    {
        public override LocString DisplayDescription { get { return Localizer.DoStr("A bred Sheep."); } }
    }
}
